#!/usr/bin/env bash
# scripts/pg_convert.sh — Converte DDL SQLite para PostgreSQL.
#
# Uso:
#   ./scripts/pg_convert.sh --all          (converte todos em databases/)
#   ./scripts/pg_convert.sh <arquivo> <schema> [saida.sql]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
DB_DIR="$ROOT_DIR/databases"
OUT_DIR="$ROOT_DIR/postgres/init"

mkdir -p "$OUT_DIR"

# ── Conversor Python inline ───────────────────────────────────────────────────

PY_CONVERTER=$(cat <<'PYEOF'
import sys, re

def convert(text, schema):
    # Remove BOM
    text = text.lstrip('﻿')
    # Remove multi-line SQL Server block comments /* ... */
    text = re.sub(r'/\*+.*?\*+/', '', text, flags=re.DOTALL)
    # Remove BEGIN TRANSACTION / COMMIT
    text = re.sub(r'^\s*BEGIN\s+TRANSACTION\s*;\s*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'^\s*COMMIT\s*;\s*$', '', text, flags=re.MULTILINE)
    # Remove standalone semicolons
    text = re.sub(r'^\s*;\s*$', '', text, flags=re.MULTILINE)
    # BLOB TEXT NULL/NOT NULL → "BLOB" TEXT NULL/NOT NULL
    # (BLOB é nome de coluna, não prefixo de tipo; precisa de aspas no PG)
    text = re.sub(r'\bBLOB\s+(TEXT\b)', r'"BLOB" \1', text)
    # REAL → DOUBLE PRECISION (word boundary, not inside identifiers)
    text = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', text)
    # INTEGER PRIMARY KEY AUTOINCREMENT → GENERATED BY DEFAULT AS IDENTITY
    text = re.sub(
        r'\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b',
        'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY',
        text, flags=re.IGNORECASE
    )
    # datetime('now') / date('now') / strftime
    text = re.sub(r"datetime\('now'\)", 'NOW()', text)
    text = re.sub(r"date\('now'\)", 'CURRENT_DATE', text)
    text = re.sub(r"strftime\('%s','now'\)", "EXTRACT(EPOCH FROM NOW())::INTEGER", text)
    # CREATE TABLE "NAME"( / CREATE TABLE NAME( → add IF NOT EXISTS
    text = re.sub(
        r'\bCREATE\s+TABLE\s+(?!IF\s+NOT\s+EXISTS)("?[A-Za-z_][A-Za-z0-9_"]*"?)\s*\(',
        r'CREATE TABLE IF NOT EXISTS \1 (',
        text, flags=re.IGNORECASE
    )
    # CREATE INDEX / CREATE UNIQUE INDEX → add IF NOT EXISTS
    text = re.sub(
        r'\bCREATE\s+(UNIQUE\s+)?INDEX\s+(?!IF\s+NOT\s+EXISTS)',
        r'CREATE \1INDEX IF NOT EXISTS ',
        text, flags=re.IGNORECASE
    )
    # Adiciona ';' após ')' isolado no fim de linha (fechamento de CREATE TABLE/INDEX)
    text = re.sub(r'^\)(\s*)$', r');\1', text, flags=re.MULTILINE)
    # Collapse 3+ blank lines into 1
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

schema = sys.argv[1]
infile = sys.argv[2]

with open(infile, encoding='utf-8-sig', errors='replace') as f:
    raw = f.read()

converted = convert(raw, schema)

header = f"""-- PostgreSQL DDL — schema: {schema}
-- Gerado por scripts/pg_convert.sh a partir de {infile.split('/')[-1]}
-- NÃO edite manualmente; re-execute o script para regenerar.

SET search_path = "{schema}", public;

"""

print(header + converted)
PYEOF
)

convert_file() {
  local input="$1"
  local schema="$2"
  local output="$3"
  echo "  converting: $(basename "$input") → $(basename "$output")"
  python3 -c "$PY_CONVERTER" "$schema" "$input" > "$output"
  local lines
  lines=$(wc -l < "$output")
  echo "  done: $output ($lines lines)"
}

# ── Mapeamento arquivo → schema → arquivo de saída ────────────────────────────

declare -A SCHEMA_MAP=(
  ["XORCISM_sqlite.sql"]="xorcism:02-xorcism.sql"
  ["XVULNERABILITY_sqlite.sql"]="xvulnerability:03-xvulnerability.sql"
  ["XATTACK_sqlite.sql"]="xattack:04-xattack.sql"
  ["XMALWARE_sqlite.sql"]="xmalware:05-xmalware.sql"
  ["XINCIDENT_sqlite.sql"]="xincident:06-xincident.sql"
  ["XTHREAT_sqlite.sql"]="xthreat:07-xthreat.sql"
  ["XOVAL_sqlite.sql"]="xoval:08-xoval.sql"
  ["XWINDOWS_sqlite.sql"]="xwindows:09-xwindows.sql"
)

if [[ "${1:-}" == "--all" ]]; then
  echo "Convertendo todos os arquivos DDL SQLite..."
  for filename in "${!SCHEMA_MAP[@]}"; do
    IFS=':' read -r schema outfile <<< "${SCHEMA_MAP[$filename]}"
    input="$DB_DIR/$filename"
    if [[ -f "$input" ]]; then
      convert_file "$input" "$schema" "$OUT_DIR/$outfile"
    else
      echo "  AVISO: $input não encontrado, pulando."
    fi
  done
  echo "Conversão concluída. Arquivos em $OUT_DIR/"

elif [[ $# -ge 2 ]]; then
  input="$1"
  schema="$2"
  outname="${3:-${schema}.sql}"
  convert_file "$input" "$schema" "$OUT_DIR/$outname"

else
  echo "Uso:"
  echo "  $0 --all                                    # converte todos"
  echo "  $0 <arquivo.sql> <schema> [saida.sql]       # converte um arquivo"
  exit 1
fi
