-- Flyway V2 — Tabelas base dos 13 schemas XDEFENSE
-- Este arquivo combina o DDL base de todos os schemas.
-- As tabelas de aplicação (XCOMPLIANCE, XID, XJOB, XAGENT, XTICKET)
-- são criadas aqui; as tabelas dos schemas XORCISM-XWINDOWS estão nos
-- arquivos postgres/init/02-09 e são aplicadas via docker-compose init.
--
-- NOTA: Este arquivo é usado pelo Flyway para ambientes de produção/CI.
-- O Docker compose usa postgres/init/ na inicialização do container.
-- Ambos usam IF NOT EXISTS para ser idempotentes.

-- ── XSEQ (todas as schemas) ───────────────────────────────────────────────────

SET search_path = "xorcism", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xvulnerability", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xattack", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xmalware", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xincident", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xthreat", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xoval", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xwindows", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xcompliance", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xticket", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xid", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xjob", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

SET search_path = "xagent", public;
CREATE TABLE IF NOT EXISTS XSEQ (SeqName TEXT PRIMARY KEY, Val INTEGER NOT NULL DEFAULT 0);

-- ── XID — Usuários, sessões e RBAC ───────────────────────────────────────────

SET search_path = "xid", public;

CREATE TABLE IF NOT EXISTS XUSER (
  UserID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Email TEXT NOT NULL, LoweredEmail TEXT NOT NULL UNIQUE, DisplayName TEXT,
  PasswordHash TEXT NOT NULL, IsApproved INTEGER NOT NULL DEFAULT 1,
  IsLockedOut INTEGER NOT NULL DEFAULT 0, MustChangePassword INTEGER NOT NULL DEFAULT 0,
  FailedPasswordAttemptCount INTEGER NOT NULL DEFAULT 0, FailedPasswordWindowStart TEXT,
  LastLoginDate TEXT, LastPasswordChangedDate TEXT, CreatedDate TEXT, CreatedByUserID INTEGER,
  Comment TEXT, TenantID INTEGER, PinHash TEXT, TotpSecret TEXT, TotpEnabled INTEGER
);
CREATE TABLE IF NOT EXISTS XROLE (
  RoleID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RoleName TEXT NOT NULL UNIQUE, RoleDescription TEXT, CreatedDate TEXT
);
CREATE TABLE IF NOT EXISTS XUSERROLE (
  UserRoleID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID INTEGER NOT NULL, RoleID INTEGER NOT NULL, UNIQUE(UserID, RoleID)
);
CREATE TABLE IF NOT EXISTS XPERMISSION (
  PermissionID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RoleID INTEGER NOT NULL, ResourceType TEXT NOT NULL, ResourceKey TEXT NOT NULL,
  CanCreate INTEGER NOT NULL DEFAULT 0, CanRead INTEGER NOT NULL DEFAULT 0,
  CanUpdate INTEGER NOT NULL DEFAULT 0, CanDelete INTEGER NOT NULL DEFAULT 0,
  CreatedDate TEXT, UNIQUE(RoleID, ResourceType, ResourceKey)
);
CREATE TABLE IF NOT EXISTS XSESSION (
  SessionID TEXT PRIMARY KEY, UserID INTEGER NOT NULL,
  CreatedDate TEXT NOT NULL, ExpiresDate TEXT NOT NULL, LastSeenDate TEXT, IP TEXT, UserAgent TEXT
);
CREATE TABLE IF NOT EXISTS XAUDITLOG (
  AuditID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID INTEGER, Action TEXT NOT NULL, ResourceType TEXT, ResourceKey TEXT,
  Detail TEXT, IP TEXT, Timestamp TEXT NOT NULL, TenantID INTEGER
);
CREATE TABLE IF NOT EXISTS XTENANT (
  TenantID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TenantName TEXT NOT NULL UNIQUE, IsSystem INTEGER NOT NULL DEFAULT 0,
  IsActive INTEGER NOT NULL DEFAULT 1, CreatedDate TEXT
);
CREATE TABLE IF NOT EXISTS XPASSWORDRESET (
  ResetID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID INTEGER NOT NULL, TokenHash TEXT NOT NULL UNIQUE,
  ExpiresDate TEXT NOT NULL, UsedDate TEXT, CreatedDate TEXT
);
CREATE TABLE IF NOT EXISTS XFEEDBACK (
  FeedbackID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID INTEGER, Email TEXT, Type TEXT NOT NULL DEFAULT 'rating',
  FeatureKey TEXT, Rating INTEGER, Title TEXT, Message TEXT,
  Status TEXT NOT NULL DEFAULT 'new', CreatedDate TEXT
);
CREATE TABLE IF NOT EXISTS XUSERPREF (
  UserID INTEGER NOT NULL, PrefKey TEXT NOT NULL, PrefValue TEXT, ModifiedDate TEXT,
  PRIMARY KEY (UserID, PrefKey)
);
CREATE TABLE IF NOT EXISTS XAPIKEY (
  KeyID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID INTEGER NOT NULL, TenantID INTEGER, Name TEXT NOT NULL,
  Prefix TEXT NOT NULL, KeyHash TEXT NOT NULL UNIQUE, Scopes TEXT,
  CreatedDate TEXT NOT NULL, LastUsedDate TEXT, ExpiresDate TEXT, Revoked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS XWEBAUTHN (
  CredentialID TEXT PRIMARY KEY, UserID INTEGER NOT NULL, PublicKeyJwk TEXT NOT NULL,
  Alg INTEGER NOT NULL, SignCount INTEGER NOT NULL DEFAULT 0, Transports TEXT,
  Aaguid TEXT, Name TEXT, CreatedDate TEXT, LastUsedDate TEXT
);
CREATE TABLE IF NOT EXISTS XWEBHOOK (
  WebhookID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID INTEGER NOT NULL, TenantID INTEGER, Url TEXT NOT NULL, Secret TEXT NOT NULL,
  Events TEXT NOT NULL, Active INTEGER NOT NULL DEFAULT 1, CreatedDate TEXT NOT NULL,
  LastStatus INTEGER, LastDeliveryDate TEXT, FailureCount INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS XRBACSEED (name TEXT PRIMARY KEY, applied_at TEXT);

CREATE INDEX IF NOT EXISTS ix_user_tenant   ON XUSER(TenantID);
CREATE INDEX IF NOT EXISTS ix_userrole_user ON XUSERROLE(UserID);
CREATE INDEX IF NOT EXISTS ix_perm_role     ON XPERMISSION(RoleID);
CREATE INDEX IF NOT EXISTS ix_session_user  ON XSESSION(UserID);
CREATE INDEX IF NOT EXISTS ix_audit_user    ON XAUDITLOG(UserID);
CREATE INDEX IF NOT EXISTS ix_reset_user    ON XPASSWORDRESET(UserID);
CREATE INDEX IF NOT EXISTS ix_webauthn_user ON XWEBAUTHN(UserID);
CREATE INDEX IF NOT EXISTS ix_webhook_user  ON XWEBHOOK(UserID);

-- ── XTICKET ───────────────────────────────────────────────────────────────────

SET search_path = "xticket", public;

CREATE TABLE IF NOT EXISTS TICKET (
  TicketID INTEGER PRIMARY KEY, TicketGUID TEXT, TicketNumber TEXT, Subject TEXT, Description TEXT,
  Status TEXT, Priority TEXT, Severity TEXT, TicketType TEXT, CategoryID INTEGER,
  RequesterName TEXT, RequesterEmail TEXT, AssigneeName TEXT, Tags TEXT,
  CreatedDate TEXT, UpdatedDate TEXT, DueDate TEXT, ResolvedDate TEXT, ClosedDate TEXT, Resolution TEXT
);
CREATE TABLE IF NOT EXISTS TICKETCOMMENT (
  TicketCommentID INTEGER PRIMARY KEY, TicketCommentGUID TEXT, TicketID INTEGER,
  Author TEXT, Body TEXT, IsInternal INTEGER, CreatedDate TEXT
);
CREATE TABLE IF NOT EXISTS TICKETCATEGORY (
  TicketCategoryID INTEGER PRIMARY KEY, TicketCategoryName TEXT, Description TEXT, CreatedDate TEXT
);
CREATE TABLE IF NOT EXISTS TICKETATTACHMENT (
  TicketAttachmentID INTEGER PRIMARY KEY, TicketID INTEGER, FileName TEXT, FilePath TEXT, CreatedDate TEXT
);
CREATE INDEX IF NOT EXISTS ix_ticketcomment_ticket    ON TICKETCOMMENT(TicketID);
CREATE INDEX IF NOT EXISTS ix_ticketattachment_ticket ON TICKETATTACHMENT(TicketID);

-- ── XJOB ─────────────────────────────────────────────────────────────────────

SET search_path = "xjob", public;

CREATE TABLE IF NOT EXISTS XJOB (
  JobID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector TEXT NOT NULL, params TEXT, target TEXT, engagement_id INTEGER, worker TEXT,
  status TEXT NOT NULL DEFAULT 'queued', user_id INTEGER,
  created_at TEXT, started_at TEXT, finished_at TEXT,
  exit_code INTEGER, log TEXT, result_summary TEXT, result_json TEXT, error TEXT
);
CREATE TABLE IF NOT EXISTS XENGAGEMENT (
  EngagementID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL, scope TEXT, active INTEGER DEFAULT 1,
  roe TEXT, created_at TEXT, created_by INTEGER
);
CREATE TABLE IF NOT EXISTS XWORKER (
  WorkerID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, token_hash TEXT NOT NULL, kind TEXT DEFAULT 'remote',
  capabilities TEXT, status TEXT DEFAULT 'idle', last_seen TEXT, created_at TEXT, created_by INTEGER
);
CREATE TABLE IF NOT EXISTS XSCHEDULE (
  ScheduleID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector TEXT NOT NULL, params TEXT, target TEXT, engagement_id INTEGER, worker TEXT,
  cron TEXT NOT NULL, enabled INTEGER DEFAULT 1,
  created_at TEXT, created_by INTEGER, last_run_at TEXT, last_job_id INTEGER, run_count INTEGER DEFAULT 0
);

-- ── XAGENT ───────────────────────────────────────────────────────────────────

SET search_path = "xagent", public;

CREATE TABLE IF NOT EXISTS XAGENT (
  AgentID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE, token_hash TEXT NOT NULL, asset_name TEXT,
  os TEXT, platform TEXT, version TEXT, ip TEXT, fqdn TEXT,
  status TEXT DEFAULT 'enrolled', enrolled_at TEXT, last_seen TEXT, intel_seen INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS XAGENTEVENT (
  EventID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT, type TEXT, severity TEXT, title TEXT, detail TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS XAGENTJOB (
  AgentJobID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT NOT NULL, kind TEXT NOT NULL, params TEXT,
  status TEXT DEFAULT 'pending', created_at TEXT, started_at TEXT, finished_at TEXT,
  result_summary TEXT, created_by INTEGER
);
CREATE TABLE IF NOT EXISTS XIOC (
  IOCID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ioc_type TEXT NOT NULL, value TEXT NOT NULL, source TEXT, threat TEXT, created_at TEXT,
  UNIQUE(ioc_type, value)
);
CREATE TABLE IF NOT EXISTS FORENSICTRIAGE (
  TriageID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT, asset_name TEXT, host_os TEXT, collected_at TEXT,
  summary TEXT, artifacts TEXT, flag_count INTEGER DEFAULT 0, created_at TEXT
);
CREATE TABLE IF NOT EXISTS HONEYPOTHIT (
  HitID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT NOT NULL, src_ip TEXT, src_port INTEGER, dst_port INTEGER,
  service TEXT, banner TEXT, hit_at TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS MEMORYDUMP (
  DumpID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT NOT NULL, asset_name TEXT, host_os TEXT, tool TEXT, status TEXT,
  path TEXT, size_bytes INTEGER, sha256 TEXT, ram_total_bytes INTEGER,
  started_at TEXT, finished_at TEXT, duration_sec INTEGER, error TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS LOGHUNT (
  LogHuntID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT NOT NULL, asset_name TEXT, host_os TEXT, source TEXT, event_count INTEGER,
  severity TEXT, summary TEXT, findings TEXT, techniques TEXT, model TEXT,
  ai_used INTEGER DEFAULT 0, hunt_id INTEGER, created_at TEXT
);
CREATE TABLE IF NOT EXISTS ENDPOINTQUESTION (
  QuestionID INTEGER PRIMARY KEY, QuestionGUID TEXT, SensorID TEXT, SensorName TEXT,
  Text TEXT, Filter TEXT, AskedByUserID INTEGER, AskedByName TEXT,
  TargetCount INTEGER, Status TEXT, AskedAt TEXT, TenantID INTEGER
);
CREATE TABLE IF NOT EXISTS ENDPOINTANSWER (
  AnswerID INTEGER PRIMARY KEY, QuestionID INTEGER, Agent TEXT, Value TEXT, CreatedAt TEXT
);
CREATE TABLE IF NOT EXISTS AIAGENT (
  AiAgentID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT NOT NULL, host TEXT, host_os TEXT, name TEXT, framework TEXT, model TEXT,
  endpoint TEXT, pid INTEGER, uses_tools INTEGER, autonomous INTEGER, has_memory INTEGER,
  external_data INTEGER, guardrail_tools TEXT, secrets_exposed INTEGER, mcp_servers INTEGER,
  logging INTEGER, sandboxed INTEGER, model_pinned INTEGER, score INTEGER, coverage INTEGER,
  gaps TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS AIGUARDRAILRESULT (
  ResultID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_agent_id INTEGER, agent TEXT, name TEXT, control_id TEXT, status TEXT, evidence TEXT, created_at TEXT
);
CREATE TABLE IF NOT EXISTS AIGUARDRAILVIOLATION (
  ViolationID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent TEXT, host TEXT, ai_agent TEXT, technique TEXT, name TEXT, severity TEXT,
  evidence TEXT, source TEXT, ai_used INTEGER DEFAULT 0, hunt_id INTEGER, created_at TEXT
);
CREATE INDEX IF NOT EXISTS ix_agentevent_agent     ON XAGENTEVENT(agent);
CREATE INDEX IF NOT EXISTS ix_agentjob_agent       ON XAGENTJOB(agent, status);
CREATE INDEX IF NOT EXISTS ix_forensictriage_agent ON FORENSICTRIAGE(agent);
CREATE INDEX IF NOT EXISTS ix_honeypothit_agent    ON HONEYPOTHIT(agent, HitID);
CREATE INDEX IF NOT EXISTS ix_memorydump_agent     ON MEMORYDUMP(agent, DumpID);
CREATE INDEX IF NOT EXISTS ix_loghunt_agent        ON LOGHUNT(agent, LogHuntID);
CREATE INDEX IF NOT EXISTS ix_epquestion_tenant    ON ENDPOINTQUESTION(TenantID);
CREATE INDEX IF NOT EXISTS ix_epanswer_q           ON ENDPOINTANSWER(QuestionID);
CREATE INDEX IF NOT EXISTS ix_aiagent_agent        ON AIAGENT(agent, AiAgentID);
CREATE INDEX IF NOT EXISTS ix_aigrresult_agent     ON AIGUARDRAILRESULT(ai_agent_id);
CREATE INDEX IF NOT EXISTS ix_aigrviol_agent       ON AIGUARDRAILVIOLATION(agent, ViolationID);

-- ── Grants finais ─────────────────────────────────────────────────────────────

DO $$
DECLARE
  s TEXT;
  schemas TEXT[] := ARRAY[
    'xorcism','xvulnerability','xattack','xmalware','xincident',
    'xthreat','xoval','xwindows','xcompliance','xticket','xid','xjob','xagent'
  ];
BEGIN
  FOREACH s IN ARRAY schemas LOOP
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO xdefense_app', s);
    EXECUTE format('GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA %I TO xdefense_app', s);
    EXECUTE format('GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA %I TO xdefense_app', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT ALL PRIVILEGES ON TABLES TO xdefense_app', s);
    EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT ALL PRIVILEGES ON SEQUENCES TO xdefense_app', s);
  END LOOP;
END;
$$;
