-- PostgreSQL DDL — schema: xoval
-- Gerado por scripts/pg_convert.sh a partir de XOVAL_sqlite.sql
-- NÃO edite manualmente; re-execute o script para regenerar.

SET search_path = "xoval", public;

CREATE TABLE IF NOT EXISTS "OPERATORENUMERATION" (
	"OperatorEnumerationID" INTEGER NOT NULL,
	"OperatorValue" TEXT NOT NULL,
	"OperatorDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALBEHAVIOR" (
	"OVALBehaviorID" INTEGER NOT NULL,
	"BehaviorKey" TEXT NULL,
	"BehaviorValue" TEXT NULL,
	"BehaviorID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALBEHAVIORFOROVALOBJECT" (
	"OVALObjectBehaviorID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"OVALBehaviorID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL,
	"VocabularyID" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCLASSDIRECTIVES" (
	"OVALClassDirectivesID" INTEGER NOT NULL,
	"OVALClassEnumerationID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCLASSDIRECTIVESFOROVALDIRECTIVES" (
	"OVALDirectivesID" INTEGER NOT NULL,
	"OVALClassDirectivesID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCLASSDIRECTIVESFOROVALRESULTS" (
	"OVALResultsID" INTEGER NOT NULL,
	"OVALClassDirectivesID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCLASSENUMERATION" (
	"OVALClassEnumerationID" INTEGER NOT NULL,
	"OVALClassEnumerationGUID" TEXT NULL,
	"ClassValue" TEXT NOT NULL,
	"ClassDescription" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCOMPONENTGROUP" (
	"OVALComponentGroupID" INTEGER NOT NULL,
	"OVALVariableID" INTEGER NULL,
	"OVALFunctionID" INTEGER NULL,
	"FunctionName" TEXT NULL,
	"FunctionOperation" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"isEncrypted" INTEGER NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIA" (
	"OVALCriteriaID" INTEGER NOT NULL,
	"OperatorEnumerationID" INTEGER NULL,
	"negate" INTEGER NULL,
	"comment" TEXT NULL,
	"applicabilitycheck" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIACRITERION" (
	"OVALCriteriaCriterionID" INTEGER NOT NULL,
	"OVALCriteriaID" INTEGER NOT NULL,
	"negate" INTEGER NULL,
	"OVALTestID" INTEGER NULL,
	"comment" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIAEXTENDDEFINITION" (
	"OVALCriteriaExtendDefinitionID" INTEGER NOT NULL,
	"OVALCriteriaID" INTEGER NOT NULL,
	"negate" INTEGER NULL,
	"OVALDefinitionID" INTEGER NULL,
	"comment" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIAFOROVALCRITERIA" (
	"OVALCriteriaRelationshipID" INTEGER NOT NULL,
	"OVALCriteriaRefID" INTEGER NOT NULL,
	"RelationshipName" TEXT NULL,
	"OVALCriteriaSubjectID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"CriteriaRank" INTEGER NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIATYPE" (
	"OVALCriteriaTypeID" INTEGER NOT NULL,
	"OperatorEnumerationID" INTEGER NOT NULL,
	"OperatorValue" TEXT NOT NULL,
	"negate" INTEGER NULL,
	"ResultEnumerationID" INTEGER NOT NULL,
	"applicability_check" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIATYPEFOROVALDEFINITIONTYPE" (
	"OVALDefinitionTypeID" INTEGER NOT NULL,
	"OVALCriteriaTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERION" (
	"OVALCriterionID" INTEGER NOT NULL,
	"OVALTestIDPattern" TEXT NOT NULL,
	"negate" INTEGER NULL,
	"comment" TEXT NULL,
	"applicabilitycheck" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIONTYPE" (
	"OVALCriterionTypeID" INTEGER NOT NULL,
	"OVALTestID" INTEGER NULL,
	"OVALTestIDPattern" TEXT NOT NULL,
	"OVALTestVersion" INTEGER NOT NULL,
	"variable_instance" INTEGER NULL,
	"negate" INTEGER NULL,
	"ResultEnumerationID" INTEGER NOT NULL,
	"applicability_check" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALCRITERIONTYPEFOROVALCRITERIATYPE" (
	"OVALCriteriaTypeID" INTEGER NOT NULL,
	"OVALCriterionTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFAULTDIRECTIVES" (
	"OVALDefaultDirectivesID" INTEGER NOT NULL,
	"include_source_definitions" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITION" (
	"OVALDefinitionID" INTEGER NOT NULL,
	"OVALDefinitionIDPattern" TEXT NOT NULL,
	"OVALDefinitionVersion" INTEGER NOT NULL,
	"OVALClassEnumerationID" INTEGER NULL,
	"deprecated" INTEGER NULL,
	"OVALDefinitionTitle" TEXT NULL,
	"OVALDefinitionDescription" TEXT NULL,
	"notes" TEXT NULL,
	"OVALCriteriaID" INTEGER NULL,
	"signature" TEXT NULL,
	"StatusName" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONCCE" (
	"OVALDefinitionCCEID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NOT NULL,
	"CCEID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONCHANGE" (
	"OVALDefinitionChangeID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ChangeDate" TEXT NULL,
	"ChangeTypeName" TEXT NULL,
	"ChangeValue" TEXT NULL,
	"ChangeComment" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONCHANGES" (
	"OVALDefinitionChangesID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"OVALDefinitionChangeID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"OrganisationID" INTEGER NULL,
	"PersonID" INTEGER NULL,
	"AuthorID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONCPE" (
	"OVALDefinitionCPEID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"OVALDefinitionCPERelationship" TEXT NULL,
	"CPEID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONFAMILY" (
	"OVALDefinitionFamilyID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"OSFamilyID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL,
	"VocabularyID" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONORGANISATION" (
	"OrganisationOVALDefinitionID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NOT NULL,
	"OrganisationID" INTEGER NOT NULL,
	"OrganisationRole" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONPLATFORM" (
	"OVALDefinitionPlatformID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"PlatformID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONPRODUCT" (
	"OVALDefinitionProductID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"ProductID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONREFERENCE" (
	"OVALDefinitionReferenceID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"ReferenceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONS" (
	"OVALDefinitionsID" INTEGER NOT NULL,
	"GeneratorTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONSTATUS" (
	"OVALDefinitionID" INTEGER NOT NULL,
	"StatusID" INTEGER NOT NULL,
	"StatusDate" TEXT NULL,
	"BLOB" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONTAG" (
	"OVALDefinitionTagID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"TagID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONTYPE" (
	"OVALDefinitionTypeID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"OVALDefinitionIDPattern" TEXT NOT NULL,
	"OVALDefinitionVersion" INTEGER NOT NULL,
	"variable_instance" INTEGER NULL,
	"OVALClassEnumerationID" INTEGER NULL,
	"ClassValue" TEXT NULL,
	"ResultEnumerationID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONTYPEFOROVALSYSTEMTYPE" (
	"OVALSystemTypeID" INTEGER NOT NULL,
	"OVALDefinitionTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDEFINITIONVULNERABILITY" (
	"OVALDefinitionVulnerabilityID" INTEGER NOT NULL,
	"OVALDefinitionID" INTEGER NULL,
	"OVALDefinitionVulnerabilityRelationship" TEXT NULL,
	"VulnerabilityID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALDIRECTIVE" (
	"OVALDirectiveID" INTEGER NOT NULL,
	"reported" INTEGER NOT NULL,
	"ContentEnumerationValue" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDIRECTIVES" (
	"OVALDirectivesID" INTEGER NOT NULL,
	"GeneratorTypeID" INTEGER NOT NULL,
	"OVALDefaultDirectivesID" INTEGER NOT NULL,
	"signature" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALDIRECTIVESTYPE" (
	"OVALDirectivesTypeID" INTEGER NOT NULL,
	"definition_trueOVALDirectiveID" INTEGER NOT NULL,
	"definition_falseOVALDirectiveID" INTEGER NOT NULL,
	"definition_unknownOVALDirectiveID" INTEGER NOT NULL,
	"definition_errorDirectiveID" INTEGER NOT NULL,
	"definition_not_evaluatedDirectiveID" INTEGER NOT NULL,
	"definition_not_applicableDirectiveID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALENTITYATTRIBUTEGROUP" (
	"OVALEntityAttributeGroupID" INTEGER NOT NULL,
	"SimpleDataTypeID" INTEGER NULL,
	"DataTypeName" TEXT NULL,
	"OperationEnumerationID" INTEGER NULL,
	"OperationValue" TEXT NULL,
	"mask" INTEGER NULL,
	"OVALVariableID" INTEGER NULL,
	"OVALVariableIDPattern" TEXT NULL,
	"CheckEnumerationID" INTEGER NULL,
	"EnumerationValue" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALENTITYCOMPLEXBASE" (
	"OVALEntityComplexBaseID" INTEGER NOT NULL,
	"OVALEntityAttributeGroupID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALENTITYSIMPLEBASE" (
	"OVALEntitySimpleBaseID" INTEGER NOT NULL,
	"OVALEntityAttributeGroupID" INTEGER NOT NULL,
	"SimpleBaseValue" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALEXTENSIONPOINT" (
	"ExtensionPointID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALEXTENSIONPOINTFOROVALGENERATORTYPE" (
	"GeneratorTypeID" INTEGER NOT NULL,
	"ExtensionPointID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALEXTENSIONPOINTFORSYSTEMINFO" (
	"SystemInfoID" INTEGER NOT NULL,
	"OVALExtensionPointID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALFILTER" (
	"OVALFilterID" INTEGER NOT NULL,
	"OVALStateID" INTEGER NOT NULL,
	"FilterActionValue" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALFILTERFOROVALSET" (
	"OVALSetID" INTEGER NOT NULL,
	"OVALFilterID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALGENERATORTYPE" (
	"GeneratorTypeID" INTEGER NOT NULL,
	"productname" TEXT NULL,
	"productversion" TEXT NULL,
	"schemaversion" DOUBLE PRECISION NOT NULL,
	"BLOB" TEXT NOT NULL,
	"VocabularyID" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALITEM" (
	"OVALItemID" INTEGER NOT NULL,
	"OVALItemIDPattern" TEXT NOT NULL,
	"StatusID" INTEGER NULL,
	"StatusName" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL,
	"VocabularyID" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALITEMATTRIBUTEGROUP" (
	"OVALItemAttributeGroupID" INTEGER NOT NULL,
	"DataTypeName" TEXT NULL,
	"mask" INTEGER NULL,
	"StatusName" TEXT NULL,
	"OVALItemIDPattern" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALITEMCOMPLEXBASE" (
	"OVALItemComplexBaseID" INTEGER NOT NULL,
	"OVALItemAttributeGroupID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALITEMFOROVALSYSTEMOBJECT" (
	"OVALSystemObjectID" INTEGER NOT NULL,
	"OVALItemID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALITEMSIMPLEBASE" (
	"OVALItemSimpleBaseID" INTEGER NOT NULL,
	"OVALItemAttributeGroupID" INTEGER NOT NULL,
	"EntityValue" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALLITERALCOMPONENT" (
	"OVALLiteralComponentID" INTEGER NOT NULL,
	"SimpleDataTypeID" INTEGER NULL,
	"LiteralComponentValue" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALLITERALCOMPONENTFOROVALCOMPONENTGROUP" (
	"OVALComponentGroupLiteralComponentID" INTEGER NOT NULL,
	"OVALComponentGroupID" INTEGER NOT NULL,
	"OVALLiteralComponentID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALMESSAGETYPE" (
	"MessageTypeID" INTEGER NOT NULL,
	"MessageLevelValue" TEXT NULL,
	"MessageLevelID" INTEGER NULL,
	"MessageText" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALMESSAGETYPEFOROVALDEFINITIONTYPE" (
	"OVALDefinitionTypeID" INTEGER NOT NULL,
	"OVALMessageTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALMESSAGETYPEFOROVALITEM" (
	"OVALItemID" INTEGER NOT NULL,
	"MessageTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALMESSAGETYPEFOROVALSYSTEMOBJECT" (
	"OVALSystemObjectID" INTEGER NOT NULL,
	"MessageTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALMESSAGETYPEFOROVALTESTEDITEM" (
	"OVALTestedItemID" INTEGER NOT NULL,
	"MessageTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALMESSAGETYPEFOROVALTESTTYPE" (
	"OVALTestTypeID" INTEGER NOT NULL,
	"OVALMessageTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALNAMESPACE" (
	"OVALNamespaceID" INTEGER NOT NULL,
	"OVALNamespaceName" TEXT NULL,
	"OVALNamespaceDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECT" (
	"OVALObjectID" INTEGER NOT NULL,
	"OVALObjectIDPattern" TEXT NOT NULL,
	"OVALObjectVersion" INTEGER NOT NULL,
	"OVALObjectGUID" TEXT NULL,
	"comment" TEXT NOT NULL,
	"deprecated" INTEGER NULL,
	"notes" TEXT NULL,
	"signature" TEXT NULL,
	"OVALObjectDataTypeID" INTEGER NULL,
	"OVALNamespaceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTCOMPONENT" (
	"OVALObjectComponentID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"OVALItemEntityName" TEXT NOT NULL,
	"OVALItemEntityRecord" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTCOMPONENTFOROVALCOMPONENTGROUP" (
	"OVALComponentGroupObjectComponentID" INTEGER NOT NULL,
	"OVALComponentGroupID" INTEGER NOT NULL,
	"OVALObjectComponentID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTDATATYPE" (
	"OVALObjectDataTypeID" INTEGER NOT NULL,
	"OVALObjectDataTypeName" TEXT NULL,
	"OVALObjectDataTypeDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTFIELD" (
	"OVALObjectFieldID" INTEGER NOT NULL,
	"OVALEntityAttributeGroupID" INTEGER NULL,
	"FieldName" TEXT NOT NULL,
	"OperationEnumerationID" INTEGER NULL,
	"FieldValue" TEXT NULL,
	"DataTypeName" TEXT NULL,
	"OVALNamespaceID" INTEGER NULL,
	"Namespace" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"CheckEnumerationID" INTEGER NULL,
	"OVALVariableID" INTEGER NULL,
	"VarRef" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTFIELDFOROVALOBJECTRECORD" (
	"OVALObjectRecordFieldID" INTEGER NOT NULL,
	"OVALObjectRecordID" INTEGER NOT NULL,
	"OVALObjectFieldID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTFILE" (
	"OVALObjectFileID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NULL,
	"FileID" INTEGER NULL,
	"OVALVariableID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTFOROVALSET" (
	"OVALSetObjectID" INTEGER NOT NULL,
	"OVALSetID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTFOROVALTEST" (
	"OVALTestObjectID" INTEGER NOT NULL,
	"OVALTestID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTRECORD" (
	"OVALObjectRecordID" INTEGER NOT NULL,
	"OVALObjectDataTypeID" INTEGER NULL,
	"OperationValue" TEXT NULL,
	"mask" INTEGER NULL,
	"OVALVariableIDPattern" TEXT NULL,
	"EnumerationValue" TEXT NULL,
	"OVALNamespaceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTRECORDFOROVALOBJECT" (
	"OVALObjectObjectRecordID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"OVALObjectRecordID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTTAG" (
	"OVALObjectTagID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NULL,
	"TagID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALOBJECTWINDOWSREGISTRYKEY" (
	"OVALObjectWindowsRegistryKeyID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"OVALObjectGUID" TEXT NULL,
	"operation" TEXT NULL,
	"WindowsRegistryKeyObjectID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"CreationObjectID" INTEGER NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALRESULTS" (
	"OVALResultsID" INTEGER NOT NULL,
	"GeneratorTypeID" INTEGER NOT NULL,
	"OVALDefaultDirectivesID" INTEGER NOT NULL,
	"OVALDefinitionsID" INTEGER NULL,
	"OVALResultsTypeID" INTEGER NOT NULL,
	"signature" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALRESULTSTYPE" (
	"OVALResultsTypeId" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSET" (
	"OVALSetID" INTEGER NOT NULL,
	"SetOperatorValue" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSETFOROVALSET" (
	"OVALSetRefID" INTEGER NOT NULL,
	"OVALSetSubjectID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATE" (
	"OVALStateID" INTEGER NOT NULL,
	"OVALStateIDPattern" TEXT NOT NULL,
	"OVALStateVersion" INTEGER NULL,
	"OVALStateSimpleBaseID" INTEGER NULL,
	"OVALStateComplexBaseID" INTEGER NULL,
	"OVALStateTypeID" INTEGER NULL,
	"DataTypeName" TEXT NULL,
	"OperatorEnumerationID" INTEGER NULL,
	"comment" TEXT NOT NULL,
	"deprecated" INTEGER NULL,
	"notes" TEXT NULL,
	"signature" TEXT NULL,
	"OVALNamespaceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATECOMPLEXBASE" (
	"OVALStateComplexBaseID" INTEGER NOT NULL,
	"CheckEnumerationID" INTEGER NULL,
	"EnumerationValue" TEXT NULL,
	"DataTypeName" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATEFIELD" (
	"OVALStateFieldID" INTEGER NOT NULL,
	"OVALEntityAttributeGroupID" INTEGER NULL,
	"FieldName" TEXT NULL,
	"DataTypeName" TEXT NULL,
	"OperationEnumerationID" INTEGER NULL,
	"CheckEnumerationID" INTEGER NULL,
	"FieldValue" TEXT NULL,
	"OVALNamespaceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"OVALVariableID" INTEGER NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATEFIELDFOROVALSTATERECORD" (
	"OVALStateRecordStateFieldID" INTEGER NOT NULL,
	"OVALStateRecordID" INTEGER NOT NULL,
	"OVALStateFieldID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATEFOROVALTEST" (
	"OVALTestStateID" INTEGER NOT NULL,
	"OVALTestID" INTEGER NOT NULL,
	"OVALStateID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATERECORD" (
	"OVALStateRecordID" INTEGER NOT NULL,
	"OVALStateComplexBaseID" INTEGER NULL,
	"OVALStateTypeID" INTEGER NULL,
	"DataTypeName" TEXT NOT NULL,
	"OperationEnumerationID" INTEGER NULL,
	"mask" INTEGER NULL,
	"OVALVariableID" INTEGER NULL,
	"CheckEnumerationID" INTEGER NULL,
	"OVALNamespaceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATERECORDFOROVALSTATE" (
	"OVALStateStateRecordID" INTEGER NOT NULL,
	"OVALStateID" INTEGER NOT NULL,
	"OVALStateRecordID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATESIMPLEBASE" (
	"OVALStateSimpleBaseID" INTEGER NOT NULL,
	"CheckEnumerationID" INTEGER NULL,
	"EnumerationValue" TEXT NULL,
	"EntityValue" TEXT NULL,
	"DataTypeName" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSTATETYPE" (
	"OVALStateTypeID" INTEGER NOT NULL,
	"OVALStateTypeName" TEXT NULL,
	"OVALStateTypeDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSYSTEMCHARACTERISTICS" (
	"OVALSystemCharacteristicsID" INTEGER NOT NULL,
	"GeneratorTypeID" INTEGER NOT NULL,
	"signature" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSYSTEMOBJECT" (
	"OVALSystemObjectID" INTEGER NOT NULL,
	"OVALObjectID" INTEGER NOT NULL,
	"OVALObjectIDPattern" TEXT NOT NULL,
	"OVALObjectVersion" INTEGER NOT NULL,
	"VariableInstance" INTEGER NULL,
	"comment" TEXT NULL,
	"FlagID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALSYSTEMTYPE" (
	"OVALSystemTypeID" INTEGER NOT NULL,
	"OVALSystemCharacteristicsID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALSYSTEMTYPEFOROVALRESULTSTYPE" (
	"OVALResultsTypeID" INTEGER NOT NULL,
	"OVALSystemTypeID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTEST" (
	"OVALTestID" INTEGER NOT NULL,
	"OVALTestIDPattern" TEXT NOT NULL,
	"OVALTestVersion" INTEGER NOT NULL,
	"ExistenceEnumerationID" INTEGER NULL,
	"CheckEnumerationID" INTEGER NULL,
	"OperatorEnumerationID" INTEGER NULL,
	"comment" TEXT NOT NULL,
	"deprecated" INTEGER NULL,
	"notes" TEXT NULL,
	"signature" TEXT NULL,
	"OVALTestDataTypeID" INTEGER NULL,
	"OVALNamespaceID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"RepositoryID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTDATATYPE" (
	"OVALTestDataTypeID" INTEGER NOT NULL,
	"OVALTestDataTypeName" TEXT NULL,
	"OVALTestDataTypeDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTEDITEM" (
	"OVALTestedItemID" INTEGER NOT NULL,
	"OVALItemID" INTEGER NULL,
	"OVALItemIDPattern" TEXT NOT NULL,
	"ResultEnumerationID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTEDITEMFOROVALTESTTYPE" (
	"OVALTestTypeID" INTEGER NOT NULL,
	"OVALTestedItemID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTEDVARIABLE" (
	"OVALTestedVariableID" INTEGER NOT NULL,
	"OVALVariableID" INTEGER NULL,
	"OVALVariableIDPattern" TEXT NOT NULL,
	"OVALVariableValue" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTEDVARIABLEFOROVALTESTTYPE" (
	"OVALTestTypeID" INTEGER NOT NULL,
	"OVALTestedVariableId" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTFOROVALTESTS" (
	"OVALTestsTestID" INTEGER NOT NULL,
	"OVALTestsID" INTEGER NOT NULL,
	"OVALTestID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTS" (
	"OVALTestsID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTTAG" (
	"OVALTestTagID" INTEGER NOT NULL,
	"OVALTestID" INTEGER NULL,
	"TagID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTTYPE" (
	"OVALTestTypeID" INTEGER NOT NULL,
	"OVALTestID" INTEGER NULL,
	"OVALTestIDPattern" TEXT NOT NULL,
	"OVALTestVersion" INTEGER NOT NULL,
	"variable_instance" INTEGER NULL,
	"ExistenceEnumerationID" INTEGER NULL,
	"ExistenceValue" TEXT NULL,
	"CheckEnumerationID" INTEGER NULL,
	"EnumerationValue" TEXT NOT NULL,
	"OperatorEnumerationID" INTEGER NULL,
	"OperatorValue" TEXT NULL,
	"ResultEnumerationID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALTESTTYPEFOROVALSYSTEMTYPE" (
	"OVALSystemTypeTestTypeID" INTEGER NOT NULL,
	"OVALSystemTypeID" INTEGER NOT NULL,
	"OVALTestTypeID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLE" (
	"OVALVariableID" INTEGER NOT NULL,
	"OVALVariableIDPattern" TEXT NOT NULL,
	"OVALVariableVersion" INTEGER NOT NULL,
	"OVALVariableDataTypeID" INTEGER NULL,
	"comment" TEXT NOT NULL,
	"deprecated" INTEGER NULL,
	"signature" TEXT NULL,
	"OVALNamespaceID" INTEGER NULL,
	"OVALVariableTypeID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLECOMPONENT" (
	"OVALVariableComponentID" INTEGER NOT NULL,
	"OVALVariableID" INTEGER NOT NULL,
	"OVALItemFieldName" TEXT NULL,
	"OVALObjectRefID" INTEGER NULL,
	"OVALVariableRefID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLECOMPONENTFOROVALCOMPONENTGROUP" (
	"OVALComponentGroupVariableComponentID" INTEGER NOT NULL,
	"OVALComponentGroupID" INTEGER NOT NULL,
	"OVALVariableComponentID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLEDATATYPE" (
	"OVALVariableDataTypeID" INTEGER NOT NULL,
	"OVALVariableDataTypeName" TEXT NULL,
	"OVALVariableDataTypeDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLEFOROVALVARIABLES" (
	"OVALVariablesID" INTEGER NOT NULL,
	"OVALVariableID" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLES" (
	"OVALVariablesID" INTEGER NOT NULL,
	"OVALGeneratorTypeID" INTEGER NOT NULL,
	"signature" TEXT NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLETAG" (
	"OVALVariableTagID" INTEGER NOT NULL,
	"OVALVariableID" INTEGER NULL,
	"TagID" INTEGER NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLETYPE" (
	"OVALVariableTypeID" INTEGER NOT NULL,
	"OVALVariableTypeName" TEXT NULL,
	"OVALVariableTypeDescription" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLEVALUE" (
	"OVALVariableValueID" INTEGER NOT NULL,
	"OVALVariableID" INTEGER NOT NULL,
	"OVALVariableGUID" TEXT NULL,
	"ValueID" INTEGER NOT NULL,
	"ValueValue" TEXT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL,
	"isEncrypted" INTEGER NULL,
	"VocabularyID" INTEGER NULL
);

CREATE TABLE IF NOT EXISTS "OVALVARIABLEVALUEFOROVALSYSTEMOBJECT" (
	"OVALSystemObjectVariableValueID" INTEGER NOT NULL,
	"OVALSystemObjectID" INTEGER NOT NULL,
	"OVALVariableValueID" INTEGER NOT NULL,
	"CreatedDate" TEXT NULL,
	"BLOB" TEXT NULL,
	"VocabularyID" INTEGER NULL,
	"isEncrypted" INTEGER NULL,
	"ValidFromDate" TEXT NULL,
	"ValidUntilDate" TEXT NULL
);
