-- PostgreSQL DDL — schema: xid
-- Usuários, papéis, permissões RBAC, sessões, auditoria, tenants.
-- Extraído de xorcism_ts/server/xid.ts:ensureSchema()

SET search_path = "xid", public;

CREATE TABLE IF NOT EXISTS XUSER (
  UserID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Email           TEXT NOT NULL,
  LoweredEmail    TEXT NOT NULL UNIQUE,
  DisplayName     TEXT,
  PasswordHash    TEXT NOT NULL,
  IsApproved      INTEGER NOT NULL DEFAULT 1,
  IsLockedOut     INTEGER NOT NULL DEFAULT 0,
  MustChangePassword INTEGER NOT NULL DEFAULT 0,
  FailedPasswordAttemptCount INTEGER NOT NULL DEFAULT 0,
  FailedPasswordWindowStart TEXT,
  LastLoginDate   TEXT,
  LastPasswordChangedDate TEXT,
  CreatedDate     TEXT,
  CreatedByUserID INTEGER,
  Comment         TEXT,
  -- campos multi-tenant (adicionados por addColumnIfMissing)
  TenantID        INTEGER,
  PinHash         TEXT,
  TotpSecret      TEXT,
  TotpEnabled     INTEGER
);

CREATE TABLE IF NOT EXISTS XROLE (
  RoleID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RoleName        TEXT NOT NULL UNIQUE,
  RoleDescription TEXT,
  CreatedDate     TEXT
);

CREATE TABLE IF NOT EXISTS XUSERROLE (
  UserRoleID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID     INTEGER NOT NULL,
  RoleID     INTEGER NOT NULL,
  UNIQUE (UserID, RoleID)
);

CREATE TABLE IF NOT EXISTS XPERMISSION (
  PermissionID  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RoleID        INTEGER NOT NULL,
  ResourceType  TEXT NOT NULL,
  ResourceKey   TEXT NOT NULL,
  CanCreate     INTEGER NOT NULL DEFAULT 0,
  CanRead       INTEGER NOT NULL DEFAULT 0,
  CanUpdate     INTEGER NOT NULL DEFAULT 0,
  CanDelete     INTEGER NOT NULL DEFAULT 0,
  CreatedDate   TEXT,
  UNIQUE (RoleID, ResourceType, ResourceKey)
);

CREATE TABLE IF NOT EXISTS XSESSION (
  SessionID   TEXT PRIMARY KEY,
  UserID      INTEGER NOT NULL,
  CreatedDate TEXT NOT NULL,
  ExpiresDate TEXT NOT NULL,
  LastSeenDate TEXT,
  IP          TEXT,
  UserAgent   TEXT
);

CREATE TABLE IF NOT EXISTS XAUDITLOG (
  AuditID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID       INTEGER,
  Action       TEXT NOT NULL,
  ResourceType TEXT,
  ResourceKey  TEXT,
  Detail       TEXT,
  IP           TEXT,
  Timestamp    TEXT NOT NULL,
  TenantID     INTEGER
);

CREATE TABLE IF NOT EXISTS XTENANT (
  TenantID   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  TenantName TEXT NOT NULL UNIQUE,
  IsSystem   INTEGER NOT NULL DEFAULT 0,
  IsActive   INTEGER NOT NULL DEFAULT 1,
  CreatedDate TEXT
);

CREATE TABLE IF NOT EXISTS XPASSWORDRESET (
  ResetID     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID      INTEGER NOT NULL,
  TokenHash   TEXT NOT NULL UNIQUE,
  ExpiresDate TEXT NOT NULL,
  UsedDate    TEXT,
  CreatedDate TEXT
);

CREATE TABLE IF NOT EXISTS XFEEDBACK (
  FeedbackID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID     INTEGER,
  Email      TEXT,
  Type       TEXT NOT NULL DEFAULT 'rating',
  FeatureKey TEXT,
  Rating     INTEGER,
  Title      TEXT,
  Message    TEXT,
  Status     TEXT NOT NULL DEFAULT 'new',
  CreatedDate TEXT
);

CREATE TABLE IF NOT EXISTS XUSERPREF (
  UserID      INTEGER NOT NULL,
  PrefKey     TEXT NOT NULL,
  PrefValue   TEXT,
  ModifiedDate TEXT,
  PRIMARY KEY (UserID, PrefKey)
);

CREATE TABLE IF NOT EXISTS XAPIKEY (
  KeyID       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID      INTEGER NOT NULL,
  TenantID    INTEGER,
  Name        TEXT NOT NULL,
  Prefix      TEXT NOT NULL,
  KeyHash     TEXT NOT NULL UNIQUE,
  Scopes      TEXT,
  CreatedDate TEXT NOT NULL,
  LastUsedDate TEXT,
  ExpiresDate TEXT,
  Revoked     INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS XWEBAUTHN (
  CredentialID TEXT PRIMARY KEY,
  UserID       INTEGER NOT NULL,
  PublicKeyJwk TEXT NOT NULL,
  Alg          INTEGER NOT NULL,
  SignCount    INTEGER NOT NULL DEFAULT 0,
  Transports   TEXT,
  Aaguid       TEXT,
  Name         TEXT,
  CreatedDate  TEXT,
  LastUsedDate TEXT
);

CREATE TABLE IF NOT EXISTS XWEBHOOK (
  WebhookID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  UserID       INTEGER NOT NULL,
  TenantID     INTEGER,
  Url          TEXT NOT NULL,
  Secret       TEXT NOT NULL,
  Events       TEXT NOT NULL,
  Active       INTEGER NOT NULL DEFAULT 1,
  CreatedDate  TEXT NOT NULL,
  LastStatus   INTEGER,
  LastDeliveryDate TEXT,
  FailureCount INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS XRBACSEED (
  name       TEXT PRIMARY KEY,
  applied_at TEXT
);

-- Indexes
CREATE INDEX IF NOT EXISTS ix_user_tenant    ON XUSER(TenantID);
CREATE INDEX IF NOT EXISTS ix_userrole_user  ON XUSERROLE(UserID);
CREATE INDEX IF NOT EXISTS ix_perm_role      ON XPERMISSION(RoleID);
CREATE INDEX IF NOT EXISTS ix_session_user   ON XSESSION(UserID);
CREATE INDEX IF NOT EXISTS ix_audit_user     ON XAUDITLOG(UserID);
CREATE INDEX IF NOT EXISTS ix_reset_user     ON XPASSWORDRESET(UserID);
CREATE INDEX IF NOT EXISTS ix_webauthn_user  ON XWEBAUTHN(UserID);
CREATE INDEX IF NOT EXISTS ix_webhook_user   ON XWEBHOOK(UserID);
