-- PostgreSQL DDL — schema: xjob
-- Fila de jobs, engagements, workers e schedules para execução de conectores.
-- Extraído de xorcism_ts/server/jobs.ts:getJobDb()

SET search_path = "xjob", public;

CREATE TABLE IF NOT EXISTS XJOB (
  JobID          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector      TEXT NOT NULL,
  params         TEXT,
  target         TEXT,
  engagement_id  INTEGER,
  worker         TEXT,
  status         TEXT NOT NULL DEFAULT 'queued',
  user_id        INTEGER,
  created_at     TEXT,
  started_at     TEXT,
  finished_at    TEXT,
  exit_code      INTEGER,
  log            TEXT,
  result_summary TEXT,
  result_json    TEXT,
  error          TEXT
);

CREATE TABLE IF NOT EXISTS XENGAGEMENT (
  EngagementID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  scope        TEXT,
  active       INTEGER DEFAULT 1,
  roe          TEXT,
  created_at   TEXT,
  created_by   INTEGER
);

CREATE TABLE IF NOT EXISTS XWORKER (
  WorkerID     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL UNIQUE,
  token_hash   TEXT NOT NULL,
  kind         TEXT DEFAULT 'remote',
  capabilities TEXT,
  status       TEXT DEFAULT 'idle',
  last_seen    TEXT,
  created_at   TEXT,
  created_by   INTEGER
);

CREATE TABLE IF NOT EXISTS XSCHEDULE (
  ScheduleID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  connector     TEXT NOT NULL,
  params        TEXT,
  target        TEXT,
  engagement_id INTEGER,
  worker        TEXT,
  cron          TEXT NOT NULL,
  enabled       INTEGER DEFAULT 1,
  created_at    TEXT,
  created_by    INTEGER,
  last_run_at   TEXT,
  last_job_id   INTEGER,
  run_count     INTEGER DEFAULT 0
);
